name: cue
description: Physics-first Flutter animations with a composable, timeline-driven API.
version: 0.1.2
homepage: https://github.com/Milad-Akarie/cue
repository: https://github.com/Milad-Akarie/cue
issue_tracker: https://github.com/Milad-Akarie/cue/issues
topics:
  - animation
  - motion
  - timeline
  - keyframes
  - effects

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

workspace:
  - example

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  coverage: ^1.15.0
  deminearchiver_lints: ^2.1.2
