name: cue
description: Physics-first Flutter animations with a composable, timeline-driven API.
version: 0.1.2+1
homepage: https://github.com/deminearchiver-contrib/cue
repository: https://github.com/deminearchiver-contrib/cue
issue_tracker: https://github.com/deminearchiver-contrib/cue/issues
topics: [animation, motion, timeline, keyframes, effects]
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

workspace:
  - example

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  coverage: ^1.15.0
  deminearchiver_lints: ^2.1.2
